### ISSUE TITLE
shapefile consolidé

### ISSUE THREAD

**Issue by bfrichet3** [SXONinja/ZP-Police#1]
Bonjour,

L'AGDP crée et maintent le shapefile des zones de police, consolidé avec les limites des communes (l'AGDP est source authentique en la matière).

Bonne journée,
https://www.geo.be/catalog/details/6bcbdf8f-e89f-11ec-be04-9453308970f2?l=fr

**Comment by osinthill** [comment]
Bonjour,

Je m'excuse pour ma réponse tardive et vous remercie pour l'information et les données partagées ! Je n'avais pas ces éléments lors de la création de cette carte, mais dès que possible, je mettrai à jour en conséquence.

Cordialement
